/*
 * This file was automatically generated by EvoSuite
 * Tue Jan 26 17:20:08 GFT 2016
 */

package br.edu.ufcg.splab.parsers;

import static org.evosuite.runtime.EvoAssertions.assertThrownBy;
import static org.junit.Assert.fail;

import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.Test;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(useVNET = true) 
public class EvosuiteParser_ESTest extends EvosuiteParser_ESTest_scaffolding {

  @Test
  public void test0()  throws Throwable  {
      EvosuiteParser evosuiteParser0 = new EvosuiteParser();
      // Undeclared exception!
      try { 
        evosuiteParser0.parseFile("");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("br.edu.ufcg.splab.parsers.ParseFile", e);
      }
  }
}
