/*
 * This file was automatically generated by EvoSuite
 * Tue Jan 26 17:20:56 GFT 2016
 */

package br.edu.ufcg.splab.parsers;

import static org.evosuite.runtime.EvoAssertions.assertThrownBy;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.fail;

import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.Test;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(useVNET = true) 
public class ParseFile_ESTest extends ParseFile_ESTest_scaffolding {

  @Test
  public void test0()  throws Throwable  {
      ParseFile parseFile0 = null;
      try {
        parseFile0 = new ParseFile((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("java.io.File", e);
      }
  }

  @Test
  public void test1()  throws Throwable  {
      ParseFile parseFile0 = new ParseFile("h^AY;wq7lb{");
      // Undeclared exception!
      try { 
        parseFile0.isReadyToRead();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("br.edu.ufcg.splab.parsers.ParseFile", e);
      }
  }

  @Test
  public void test2()  throws Throwable  {
      ParseFile parseFile0 = new ParseFile("7");
      // Undeclared exception!
      try { 
        parseFile0.readLine();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("br.edu.ufcg.splab.parsers.ParseFile", e);
      }
  }

  @Test
  public void test3()  throws Throwable  {
      ParseFile parseFile0 = new ParseFile("(`!u=LQ*Y,Y?O08*G");
      // Undeclared exception!
      try { 
        parseFile0.streamOff();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("br.edu.ufcg.splab.parsers.ParseFile", e);
      }
  }

  @Test
  public void test4()  throws Throwable  {
      ParseFile parseFile0 = new ParseFile("(`!u=LQ*Y,Y?O08*G");
      boolean boolean0 = parseFile0.streamOn();
      assertFalse(boolean0);
  }
}
