package br.edu.ufcg.splab.framework.techniques.selection;

import br.edu.ufcg.splab.util.testcollections.TestCase;
import br.edu.ufcg.splab.util.testcollections.TestSuite;

/*
 * Change														Author				Date
 * -------------------------------------------------------------------------------------------
 * Creation														Jose Benardi    	2016-06-15
 * 
 */
/**
 * <b>Objective:</b> Generate a sub set that is generated by members of a bigger set
 * using as parameter its dimension.
 * <br>
 * <b>Description of use:</b> In the Experiment Factory this class is used in the
 * process of building a selection.
 *
 */
public class SmallestTechnique implements InterfaceSelectionTechnique {
	
	public SmallestTechnique() {
	}
	
	/**
	 * <b>Objective:</b> Calculate the dimension of the smaller test suite.
	 * <br>
	 * <b>Example of use:</b> This method is used on the select method to help
	 * build the new test suite.
	 *
	 * @param testSuite
	 *            the test suite whose section will be separated
	 * @param percentage
	 *            the percentage desired from the test suite
	 * @return how many will be chosen.
	 */
	private int getQuantity(TestSuite testSuite, double percentage) {
		return (int) Math.ceil(testSuite.size() * percentage);
	}

	@Override
	public TestSuite select(TestSuite testSuite, Double percentage) {
		TestSuite result = new TestSuite();
		int quantity = getQuantity(testSuite, 1 - percentage);
		for (int i = 0; i < quantity; i++) {
			addSmallestTestCase(result, testSuite);
		}
		return result;
	}
	
	/**
	 * <b>Objective:</b> Add to one test suite the smallest test case from another test
	 * suite.
	 * <br>
	 * <b>Example of use:</b> This method is used on the select method to help
	 * build the new test suite.
	 * 
	 * @param result
	 *            the test suite that hold the smallest test cases.
	 * 
	 * @param testSuite
	 *            the test suite from where the smaallest will be chosen.
	 */
	private void addSmallestTestCase(TestSuite result, TestSuite testSuite) {
		int minSize = Integer.MAX_VALUE;
		int minIndex = Integer.MAX_VALUE;
		for (int i = 0; i < testSuite.size(); i++) {
			if (!result.contains(testSuite.get(i))) {
				if (testSuite.get(i).size() < minSize) {
					minSize = testSuite.get(i).size();
					minIndex = i;
				}
			}
		}
		result.add(new TestCase(testSuite.get(minIndex)));

	}
}
