package br.edu.ufcg.splab.experimentsExamples.core.dvcs;

import br.edu.ufcg.splab.arrsttFramework.IDvc;
import br.edu.ufcg.splab.arrsttFramework.util.testCollections.TestSuite;
import br.edu.ufcg.splab.experimentsExamples.util.ErrorStructure;


//WORK IN PROGRESS
public class DefectiveEdgesCollector implements IDvc {
	
	@Override
	/**
	 * <b>Objective:</b>: Calculate the amount of defective edges found in the TestSuite
	 * generated by the Executable treatment in the tuple and add it in a StringBuffer.
	 * <br>
	 * <b>Example of use</b>: In the ARRSTT Selection Experiment this method receives a SelectionTreatment
	 * so it can generate TestSuites with defective edges. The amount of those is calculated and
	 * stored in a StringBuffer that will be returned.
	 * 
	 * @param treatment
	 * 			A tuple of ExecutableTreatments that is going to generate a TestSuite.
	 * @return The StringBuffer used to store the amount of defective edges.
	 */
	public StringBuffer collect(TestSuite testSuite) {
		ErrorStructure errorStructure = new ErrorStructure(testSuite);
		return new StringBuffer(errorStructure.countDefectiveEdges() + "");
	}
	
	@Override
	public String toString() {
		return "DV DefectiveEdges";
	}

}
