package br.edu.ufcg.splab.experimentsExamples.core.dvcs;

import br.edu.ufcg.splab.arrsttFramework.IDvc;
import br.edu.ufcg.splab.arrsttFramework.util.testCollections.TestSuite;
import br.edu.ufcg.splab.experimentsExamples.util.ErrorStructure;


//WORK IN PROGRESS
public class DefectsCollector implements IDvc {

	@Override
	/**
	 * <b>Objective:</b> Calculate the amount of defects found in the TestSuite
	 * generated by the Executable treatment in the tuple and add it in a StringBuffer.
	 * <br>
	 * <b>Example of use</b>: In the ARRSTT Selection Experiment this method receives a SelectionTreatment
	 * so it can generate TestSuites with defective edges. The amount of defects is calculated and
	 * stored in a StringBuffer that will be returned.
	 * 
	 * @param treatment
	 * 			A tuple of ExecutableTreatments that is going to generate a TestSuite.
	 * @param The StringBuffer used to store the amount of defects.
	 */
	public StringBuffer collect(TestSuite testSuite) {
		ErrorStructure errorStructure = new ErrorStructure(testSuite);
		return new StringBuffer(errorStructure.countDefects() + "");
	}

	@Override
	public String toString() {
		return "DV Defects";
	}
	@Override
	public String getName(){
		return "Defects";
	}
}
